### ISSUE TITLE
Unable to import after installation of the package

### ISSUE THREAD

**Issue by aktech** [scikit-allel/skallel-stats#18]
After following the installation instructions from here:
https://github.com/scikit-allel/skallel-stats/blob/master/CONTRIBUTING.md#install-development-environment

I get the following error after importing `pairwise_distance`

```
>>> from skallel_stats.distance.api import pairwise_distance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aktech/quansight/skallel-stats/src/skallel_stats/__init__.py", line 5, in <module>
    from .distance.api import pairwise_distance
  File "/Users/aktech/quansight/skallel-stats/src/skallel_stats/distance/__init__.py", line 2, in <module>
    from . import numpy_backend
  File "/Users/aktech/quansight/skallel-stats/src/skallel_stats/distance/numpy_backend.py", line 2, in <module>
    import numba
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/__init__.py", line 45, in <module>
    import numba.typed
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/typed/__init__.py", line 3, in <module>
    from .typeddict import Dict
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/typed/typeddict.py", line 18, in <module>
    @njit
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/decorators.py", line 224, in njit
    return jit(*args, **kws)
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/decorators.py", line 161, in jit
    return wrapper(pyfunc)
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/decorators.py", line 177, in wrapper
    **dispatcher_args)
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/dispatcher.py", line 576, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/utils.py", line 381, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/targets/base.py", line 250, in __init__
    self.init()
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/targets/cpu.py", line 49, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/targets/codegen.py", line 612, in __init__
    self._init(self._llvm_module)
  File "/Users/aktech/anaconda3/envs/skallel/lib/python3.7/site-packages/numba/targets/codegen.py", line 621, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
```

**Comment by aktech** [comment]
It seems the above issue is fixed by:

```
pip install -U llvmlite==0.32.1
```

Courtesy this comment: https://github.com/rapidsai/cuml/issues/2389#issuecomment-642645437
